"""Add Explanation model

Revision ID: c2b98627dc73
Revises: 202610050001
Create Date: 2026-10-05 12:21:48.302814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b98627dc73'
down_revision: Union[str, Sequence[str], None] = '202610050001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('feature_importances', sa.JSON(), nullable=True),
    sa.Column('natural_language_explanation', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['experiment_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanations_id'), 'explanations', ['id'], unique=False)
    op.create_index(op.f('ix_explanations_model_id'), 'explanations', ['model_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explanations_model_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_id'), table_name='explanations')
    op.drop_table('explanations')
    # ### end Alembic commands ###
